### ISSUE TITLE
A few issues noted by Void

### ISSUE THREAD

**Issue by awilfox** [gavinhoward/bc#2]
In [Void Linux's issue tracker](https://github.com/void-linux/void-packages/issues/7195) they have noted a few deficiencies in this `bc`:

* The manual pages do not look good in man-db / mandoc.

* Tests are not passing, but I think this is an issue with their build recipe.

* Cross-compilation is difficult.

If I rewrote the manpages in mdoc ([example from Adélie](https://code.foxkit.us/adelie/image/raw/master/adelie-build-cd.8)) would that be acceptable?  It would look much better in normal man viewers, and could probably be converted to Markdown for viewing.

I'm not sure what they find difficult about crossing but I will try to cross it a few times and see what I find.

**Comment by gavinhoward** [comment]
Hmm...let me leave a comment there and see what happens.

Also, I was thinking about how I would convert my manuals to man pages.

**Comment by gavinhoward** [comment]
It seems that Void is okay with adding my package now. Thank you so much for reporting! I would not have been able to fix their problems without your report!

Closing as the problems seem to be taken care of.
