### ISSUE TITLE
README.md: xstatic links 404?

### ISSUE THREAD

**Issue by ibara** [gavinhoward/bc#33]
Hi Gavin --

The xstatic links (to https://pkg.musl.cc/bc/) in README.md lead to a 404. Admittedly, I don't know what those links should be pointing to.

**Comment by gavinhoward** [comment]
That link was maintained voluntarily by a friend of mine. He seems to have lost interest in maintaining the builds, and I am not going to bother him about it, so I removed those parts from the README.

Thank you for letting me know!

Windows builds will have to wait until I manage to build a build system to replace CMake. :P Until then, building on Windows doesn't seem like a good use of my time.

Unless...do you need Windows builds?

**Comment by drjohnnyfever1** [comment]
I'm probably the one guy who has used it on Windows. Its far from a must but it is a nice convenience having my bc I use on FreeBSD available when I'm on Windows. I can try mucking around with the Windows build if you think it's useful for anyone else.

**Comment by gavinhoward** [comment]
@drjohnnyfever1 getting my `bc` to work on Windows can be either easy or really hard. It depends on what you want in it.

If you want history and being able to respond to `SIGINT` (rather than just exit), then it will be hard. Otherwise, it might be fairly easy.

If you don't need those two things (which are in FreeBSD's version), then maybe I can get my Windows drive to boot and get `bc` to build under Windows.

**Comment by ibara** [comment]
I don't need a Windows binary, no. Was just curious so I clicked the link.

**Comment by ibara** [comment]
I don't think it's so difficult. We can just use some compat shims :)
Attached is bc-3.3.3 built on Windows x64 with Cygwin. Unzip and run. 
By the way, Cygwin inexplicably needs `#include <sys/socket.h>` in `src/history.c` to build history correctly. But then history is correctly detected as working by configure and builds and runs correctly. I've done that for these binaries.

[bc-3.3.3.zip](https://github.com/gavinhoward/bc/files/6095603/bc-3.3.3.zip)

**Comment by gavinhoward** [comment]
@ibara that's good to know about history. However, my hesitation is that, if I support building on Windows, I want it to actually work, and last time I tried, Cygwin had interesting behavior with POSIX signals. So I really need to get my Windows partition bootable and do some tests.

**Comment by gavinhoward** [comment]
I'm going to close this one. I may come back to making `bc` work on Windows later.
