### ISSUE TITLE
Incorrect behavior in Windows console

### ISSUE THREAD

**Issue by depler** [gavinhoward/bc#39]
Steps to reproduce:

1. Run bc.exe
2. Type any test
3. Click any arrow button

The result (text is mixed with random chars):
![image](https://user-images.githubusercontent.com/13541699/134770796-cdc12870-4b12-4db3-8219-fedcd89fe145.png)

The problem is gone if compiled with `BC_ENABLE_HISTORY=0`

**Comment by gavinhoward** [comment]
Oof. I'll investigate this.

**Comment by gavinhoward** [comment]
After investigation, I think Windows still does not have VT escape sequences right. I disabled history on Windows in commit ba792e05c9025ea994da24412e07b733aaf5a497.

Can you pull and test for me, please?

**Comment by depler** [comment]
Working fine now
