### ISSUE TITLE
forced usage of CFLAGS, STRIP etc in Makefile

### ISSUE THREAD

**Issue by rofl0r** [gavinhoward/bc#4]
it's quite uncommon to have different targets like `release`, `debug`, etc in a Makefile, but nothing speaking against it.

usually instead of using `make release` it's done like `make CFLAGS=-O3 LDFLAGS=-s`

**but** what's IMO nasty is that you force these things also onto the `all` target.
in a well-behaving makefile, there's usually one default for optimization level (typically `-O2 -g`) which is user-overridable, e.g.:
```make
CFLAGS ?= -O2 -g

-include config.mak
```
it's not a huge deal, since using my PR #3 i can circumvent the `all` target now by running `make install` directly, so the Makefile doesn't mess with my `CFLAGS`.

**Comment by gavinhoward** [comment]
Fixed, per conversation on IRC.
