### ISSUE TITLE
Switch "-q" is ignored

### ISSUE THREAD

**Issue by depler** [gavinhoward/bc#40]
Steps to reproduce:

1. Start command line `bc.exe -q`

The result:
![image](https://user-images.githubusercontent.com/13541699/134770848-8856a057-e4cf-4ca1-96a6-42231c526af0.png)

Similar case:
![image](https://user-images.githubusercontent.com/13541699/134770963-ab9817e4-57cc-4dff-8c3f-57b5a8d8c3d0.png)

**Comment by gavinhoward** [comment]
This is surprising, but I'll investigate it. Should be a simple fix.

**Comment by gavinhoward** [comment]
This was fixed by 5bc06dd2713ed060cfb74a4f6d237dea2f3b21e3. It turns out that I was handling arguments before setting the default.

**Comment by gavinhoward** [comment]
Actually, before I close this, can you test the latest commit?

**Comment by depler** [comment]
Working fine now
