### ISSUE TITLE
Test dc\vars.txt is failed on Windows (possibly other platforms too)

### ISSUE THREAD

**Issue by depler** [gavinhoward/bc#41]
See this pull request for Windows tests: https://github.com/gavinhoward/bc/pull/38

![image](https://user-images.githubusercontent.com/13541699/134770915-23df493a-d8c5-43d6-a9f7-c85dd1cad1c3.png)

**Comment by gavinhoward** [comment]
Ouch. The test does work on other platforms. I have no idea why not Windows. I'll investigate this.

**Comment by gavinhoward** [comment]
I found the problem: the `dc` tests need to be passed the `-x` command-line flag. This was fixed in f85dd7ad3f9f0b80028d04e931729bb398a5c7b8.

Can you test this along with the other fixes?

**Comment by depler** [comment]
Working fine now
