### ISSUE TITLE
Divergence from grammar defined by POSIX

### ISSUE THREAD

**Issue by oguz-ismail** [gavinhoward/bc#48]
Observe:
```
$ bc -s <<x
define a(){
}define b(){
}
x

Parse error: bad token
    <stdin>:2

$ bc -s <<x
define a(){
};define b(){
}
x
$
```
As per POSIX, the first one should work fine, and the second should fail as a newline is required after a `semicolon_list` production. No other bc implementation exhibits this behavior except busybox bc, which is a fork of this one if I recall correctly.

**Comment by gavinhoward** [comment]
This has (hopefully) been fixed in commits 5b2fe303c8c7d85d299b6576f62c8191e492fdb0, 81f838f657a2b942a76c1240d1107a4d358fd2a2, and 9ffdd5ec6915bc01fa0ceb7f5b5e9e4327615044.

Could you please pull down those commits and test? If they work, I'll release an update soon.

**Comment by gavinhoward** [comment]
Oh, I meant to say that I looked at the standard, and I agree with you on the interpretation of it.

**Comment by oguz-ismail** [comment]
@gavinhoward  Yeah, it works fine now. Thanks for the fix

**Comment by gavinhoward** [comment]
Thank you!

I'll run my release process and put out `5.2.1` as soon as it passes.

**Comment by gavinhoward** [comment]
`5.2.1` is out. I believe that solves this issue, so I am going to close. Feel free to reopen if you need to.

Thank you for your report!
