### ISSUE TITLE
Multi-line comments in files result in parse error

### ISSUE THREAD

**Issue by DelilahHoare** [gavinhoward/bc#50]
Comments delimited by `/* */` and spanning multiple lines in files result in `Parse error: comment end cannot be found`.  Such comments are accepted into stdin.

**Comment by gavinhoward** [comment]
That does sound like a bug.

Could you send me the output of `bc --version`? Also, could you send me one or more files that cause it to happen?

**Comment by DelilahHoare** [comment]
I should clarify that this only happens when using the `-f` flag; passing the file as an argument without that flag works.

```
bc 5.2.2
Copyright (c) 2018-2021 Gavin D. Howard and contributors
Report bugs at: https://git.yzena.com/gavin/bc

This is free software with ABSOLUTELY NO WARRANTY.
```

[testoneline.bc](https://github.com/gavinhoward/bc/files/8189282/testoneline.bc.txt) works,
[testmultiline.bc](https://github.com/gavinhoward/bc/files/8189281/testmultiline.bc.txt) doesn't.  
[timeconst.bc](https://github.com/gavinhoward/bc/files/8189283/timeconst.bc.txt) comes from the linux source tree and also doesn't work.

**Comment by gavinhoward** [comment]
Thank you. I have confirmed the bug, and I'm working on debugging and a fix.

**Comment by gavinhoward** [comment]
Okay, I have found the problem and have committed a fix in d778d0b9177c75f207dca16b57974edbb5f9e15c and dbc4dc4c4e94712fa1d4800c81e84d6da18f5188.

Could you pull and test the updated commits for me, to make sure they work for you? In the meantime, I'll prepare a release with the fix.

**Comment by DelilahHoare** [comment]
It's working, thanks!

**Comment by gavinhoward** [comment]
Great! I'll have version `5.2.3` out in a few days.

**Comment by gavinhoward** [comment]
`5.2.3` is out!
