### ISSUE TITLE
Release tarballs in `gzip` format

### ISSUE THREAD

**Issue by firasuke** [gavinhoward/bc#52]
Is it possible to provide release tarballs in `gzip` format as well for limited systems?

Thanks!

**Comment by gavinhoward** [comment]
Yes, absolutely.

Just to be sure, you mean `.tar.gz` files, correct?

**Comment by firasuke** [comment]
Yup, if possible.

**Comment by gavinhoward** [comment]
Not a problem. I have a new release coming out soon, and I will be sure to have `.tar.gz` files for it, as well as every future release.

**Comment by firasuke** [comment]
Thanks!

Closing this now.
