### ISSUE TITLE
Scale argument is ignored

### ISSUE THREAD

**Issue by depler** [gavinhoward/bc#55]
Hi! Here is my command line: `bc.exe --mathlib --leading-zeroes --no-line-length --scale=100`. 

Last argument is ignored by some reason.  As I see it `--mathlib` is overriding `scale` value

**Comment by gavinhoward** [comment]
Nice to have you back! Sorry that I rejected your original feature request for `--scale`; I was wrong to do so.

I have reproduced the issue. I think you are right with what is happening.

I'll get to work on fixing it.

**Comment by gavinhoward** [comment]
Stupid GitHub automatically closing issues.

Can you please pull the latest `master` and check if it does what you want? In the meantime, I'll get started on the release process.

**Comment by depler** [comment]
Yep, it works now. Thanks!

**Comment by gavinhoward** [comment]
Yay! Version `6.0.2` should come out in the next day or two. Thank you for your report!

**Comment by gavinhoward** [comment]
It's taking a little longer to get the release out. There are problems with FreeBSD. I need to fix those problems before I release. I'm sorry.

I'll let you know when `6.0.2` is out.

**Comment by gavinhoward** [comment]
`6.0.2` is out.

That should fix the issue for you. Feel free to reopen if it does not.
